name: STM32 CMake Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (master branch)
      uses: actions/checkout@v4

    - name: Install ARM GCC toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: build
      run: cmake ..

    - name: Build with Make
      working-directory: build
      run: make -j$(nproc)

    - name: List build output files
      working-directory: build
      run: ls -l

    - name: Setup gh-pages branch workspace
      run: |
        set -e
        # 如果 gh-pages 目录不存在则初始化git仓库
        if [ ! -d gh-pages ]; then
          mkdir gh-pages
          cd gh-pages
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          # 检查远程是否有gh-pages分支
          if git ls-remote --exit-code --heads origin gh-pages; then
            git fetch origin gh-pages
            git checkout -b gh-pages origin/gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push -u origin gh-pages
          fi
          cd ..
        fi

    - name: Copy build artifacts to gh-pages
      run: |
        cp -r build/* gh-pages/

    - name: Commit and push build artifacts to gh-pages
      run: |
        cd gh-pages
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto update build artifacts from master"
        git push origin gh-pages
